datastore:
  build: .
  volumes:
    - /storage/htpc/data:/data
sabnzbd:
  image: funkypenguin/sabnzbd
  volumes:
    - /storage/htpc/sabnzbd/config:/config
  volumes_from:
    - datastore
  links:
    - plex
  restart: always
  environment:
    - VIRTUAL_HOST=sabnzbd.local
    - VIRTUAL_PORT=8080
couchpotato:
  image: funkypenguin/couchpotato
  volumes:
    - /storage/htpc/couchpotato/config:/config
  volumes_from:
    - datastore
  links:
    - sabnzbd
    - plex
  restart: always
  environment:
    - VIRTUAL_HOST=couchpotato.three-five.bshaw.io,couchpotato.local
    - VIRTUAL_PORT=5050
    - LETSENCRYPT_HOST=couchpotato.three-five.bshaw.io
    - LETSENCRYPT_EMAIL=brian.b.shaw@gmail.com
plex:
  image: funkypenguin/plex
  volumes:
    - /storage/htpc/plex/config:/config
  volumes_from:
    - datastore
  restart: always
  environment:
    - VIRTUAL_HOST=plex.three-five.bshaw.io,plex.local
    - VIRTUAL_PORT=32400
    - LETSENCRYPT_HOST=plex.three-five.bshaw.io
    - LETSENCRYPT_EMAIL=brian.b.shaw@gmail.com
nzbdrone:
  image: funkypenguin/nzbdrone
  volumes:
    - /storage/htpc/nzbdrone/config:/config
  volumes_from:
    - datastore
  links:
    - sabnzbd
    - plex
  restart: always
  environment:
    - VIRTUAL_HOST=sonarr.three-five.bshaw.io,sonarr.local
    - VIRTUAL_PORT=8989
    - LETSENCRYPT_HOST=sonarr.three-five.bshaw.io
    - LETSENCRYPT_EMAIL=brian.b.shaw@gmail.com
