datastore:
  build: .
  volumes:
    - /storage/htpc/data:/data
sabnzbd:
  image: funkypenguin/sabnzbd
  volumes:
    - /storage/htpc/sabnzbd/config:/config
  volumes_from:
    - datastore
  ports:
    - 8080:8080
  links:
    - plex
  restart: always
couchpotato:
  image: funkypenguin/couchpotato
  volumes:
    - /storage/htpc/couchpotato/config:/config
  volumes_from:
    - datastore
  ports:
    - 5050:5050
  links:
    - sabnzbd
    - plex
  restart: always
plex:
  image: funkypenguin/plex
  volumes:
    - /storage/htpc/plex/config:/config
  volumes_from:
    - datastore
  ports:
    - 32400:32400
  restart: always
nzbdrone:
  image: funkypenguin/nzbdrone
  volumes:
    - /storage/htpc/nzbdrone/config:/config
  volumes_from:
    - datastore
  ports:
    - 8989:8989
  links:
    - sabnzbd
    - plex
  restart: always
